<?php

namespace CrmBundle\Repository\Back;

/**
 * CrmParamStatutTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CrmParamStatutTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
