<?php

namespace CrmBundle\Repository\Back;

/**
 * CrmParamAlertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CrmParamAlertRepository extends \Doctrine\ORM\EntityRepository
{
}
