<?php

namespace CrmBundle\Repository\Back;

/**
 * CrmParamCyclesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CrmParamCyclesDetailsActivityRepository extends \Doctrine\ORM\EntityRepository
{
}
