<?php

namespace CrmBundle\Repository\Back;

/**
 * CrmParamPrioritesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CrmParamPrioritesRepository extends \Doctrine\ORM\EntityRepository
{
}
