<?php

namespace CrmBundle\Repository\Back;

/**
 * CrmParamStatutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CrmParamStatutRepository extends \Doctrine\ORM\EntityRepository
{
}
