<?php

namespace CrmBundle\Repository\Back;

/**
 * JalonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CrmParamModeAccessRepository extends \Doctrine\ORM\EntityRepository
{
}
