<?php

namespace CrmBundle\Repository\Common;

/**
 * CrmEtapesRealisationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CrmEtapesRealisationsRepository extends \Doctrine\ORM\EntityRepository
{
}
