<?php

namespace CrmBundle\Repository\Common;

/**
 * CrmEtapesUsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CrmEtapesUsersRepository extends \Doctrine\ORM\EntityRepository
{
}
