<?php

namespace CrmBundle\Repository\Common;

/**
 * CrmDocsEnvoyesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CrmEtapesRepository extends \Doctrine\ORM\EntityRepository
{
}
