<?php

namespace CrmBundle\Repository\Common;

/**
 * CrmOperationsUsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CrmOperationsUsersRepository extends \Doctrine\ORM\EntityRepository
{
	// find one
	public function findOneBys ($user, $dateDebut, $dateFin)
	{
		$between = [
			// '(o.datedebut < :dateDebut AND o.datefin < :dateFin AND o.datefin > :dateDebut)',// intervalle A1
			// '(o.datedebut > :dateDebut AND o.datefin > :dateFin AND o.datedebut < :dateFin)', // intervalle A1
			'(o.datedebut < :dateDebut AND o.datefin > :dateFin)', // intervalle A4 inside
			'((o.datedebut BETWEEN :dateDebut AND :dateFin) AND (o.datefin BETWEEN :dateDebut AND :dateFin))', // intervalle A4 inside
		];

		$dateDebut = str_replace('-', '/', $dateDebut);
		$dateFin = str_replace('-', '/', $dateFin);

		$return = $this->createQueryBuilder('o')
			->where('o.idUser = :idUser AND ('. implode(' OR ', $between) .')')
			->setParameters(['idUser' => $user, 'dateDebut' => date('Y/m/d H:i:s', strtotime($dateDebut)), 'dateFin' => date('Y/m/d H:i:s', strtotime($dateFin))]);

		/** for debugging **/
		// $q = $return->getQuery();
		// dump($q);
		// dump($q->execute());
		// exit;

        // return
        $return = $return->getQuery()->execute();
        return count($return) ? $return : null;
	}
}