<?php

namespace MailBundle\Repository;

/**
 * FitlreSessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FitlreSessionRepository extends \Doctrine\ORM\EntityRepository
{
	
}
