<?php

namespace MailBundle\Repository;

/**
 * MailPJRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailPJRepository extends \Doctrine\ORM\EntityRepository
{
}
