<?php

namespace MailBundle\Repository;

/**
 * MailFiltreSessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailFiltreSessionRepository extends \Doctrine\ORM\EntityRepository
{
}
