<?php

namespace MailBundle\Repository;

/**
 * MailSpamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailSpamRepository extends \Doctrine\ORM\EntityRepository
{
}
