<?php

namespace MailBundle\Repository;

/**
 * MailHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailHistoryRepository extends \Doctrine\ORM\EntityRepository
{
}
