<?php

namespace MailBundle\Repository;

/**
 * ParamMailPrioritesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParamMailPrioritesRepository extends \Doctrine\ORM\EntityRepository
{
}
