<?php

namespace MailBundle\Repository;

/**
 * ParamMailTboxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParamMailTboxRepository extends \Doctrine\ORM\EntityRepository
{
}
