<?php

namespace MailBundle\Repository;

/**
 * ParamMailTsujetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParamMailTsujetRepository extends \Doctrine\ORM\EntityRepository
{
}
