<?php

namespace AppBundle\Repository\Common;

/**
 * langageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class langageRepository extends \Doctrine\ORM\EntityRepository
{
}
