<?php

namespace AppBundle\Repository\Common;

/**
 * UsersSessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersSessionRepository extends \Doctrine\ORM\EntityRepository
{
}
