<?php

namespace AppBundle\Repository;

/**
 * typeCompaignRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class typeCompaignRepository extends \Doctrine\ORM\EntityRepository
{
}
