users_user_docs:
    resource: "@UsersBundle/Controller/UserDocsController.php"
    type:     annotation

users_user_notes:
    resource: "@UsersBundle/Controller/UserNotesController.php"
    type:     annotation

client:
    resource: "@ClientBundle/Resources/config/routing.yml"
    prefix:   /

pdf:
    resource: "@PrintPDFBundle/Resources/config/routing.yml"
    prefix:   /

mail:
    resource: "@MailBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

crm:
    resource: "@CrmBundle/Resources/config/routing.yml"
    prefix:   /

project:
    resource: "@ProjectBundle/Resources/config/routing.yml"
    prefix:   /

users:
    resource: "@UsersBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'