<?php

namespace ProjectBundle\Repository\Back;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityJRepository extends \Doctrine\ORM\EntityRepository
{
}
