<?php

namespace ProjectBundle\Repository\Back;

/**
 * JalonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JalonRepository extends \Doctrine\ORM\EntityRepository
{
}
