<?php

namespace ProjectBundle\Repository\Back;

/**
 * PrioritesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrioritesRepository extends \Doctrine\ORM\EntityRepository
{
}
