<?php

namespace ProjectBundle\Repository\Back;

/**
 * ProjectAlertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectAlertRepository extends \Doctrine\ORM\EntityRepository
{
}
