<?php

namespace ProjectBundle\Repository\Back;
use Doctrine\ORM\Query\Expr\Join;

/**
 * workshopRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RolesRepository extends \Doctrine\ORM\EntityRepository
{
	// finfing by user
	public function findUsers () 
	{
		// id leader
		$idLeader = 1;
		$user_leader = $this->_em->getRepository('UsersBundle:Users')->findBy(['type' => $idLeader]);
		return $user_leader;
	}
}