<?php

namespace ProjectBundle\Repository\Back;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * StatutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatutRepository extends \Doctrine\ORM\EntityRepository
{
	// getting with pagination
	public function getWithPagination($criteria = [], $page, $max_per_page = 10)
	{
		$qb = $this->createQueryBuilder('statut');
                $qb->select('statut');

                $key = [];
                if( count($criteria) ) {
                	foreach($criteria as $k => $v)
                		$key[] = "statut.{$k} = :$k";
                	$qb->where(implode(' AND ', $key));

                	foreach($criteria as $k => $v)
                        $qb->setParameter("{$k}", $v);
                }

                $qb->setFirstResult($page);
                $qb->setMaxResults($max_per_page);

                $pag = new Paginator($qb);
                return $pag;
	}
}