<?php

namespace ProjectBundle\Repository\Back;



/**
 * statutTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class statutTypeRepository extends \Doctrine\ORM\EntityRepository
{

}