<?php

namespace ProjectBundle\Repository\Back;

/**
 * workshopRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class workshopRepository extends \Doctrine\ORM\EntityRepository
{
}