<?php

namespace ProjectBundle\Repository\Agenda;

/**
 * AgendaParamPrioriteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgendaParamPrioriteRepository extends \Doctrine\ORM\EntityRepository
{
}
