<?php

namespace ProjectBundle\Repository\Agenda;

/**
 * AgendaParamTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgendaParamTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
