<?php

namespace ProjectBundle\Repository\Agenda;

/**
 * AgendaParamAlerteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgendaParamAlerteRepository extends \Doctrine\ORM\EntityRepository
{
}
