<?php

namespace ProjectBundle\Repository\Agenda;

/**
 * AgendaParamLieuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgendaParamLieuRepository extends \Doctrine\ORM\EntityRepository
{
}
