<?php

namespace ClientBundle\Repository;

/**
 * ClientFilterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientFilterRepository extends \Doctrine\ORM\EntityRepository
{
}
