<?php

namespace ClientBundle\Repository;

/**
 * CodePostalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CodePostalRepository extends \Doctrine\ORM\EntityRepository
{

	public function findDistinct () {
		return $this->createQueryBuilder('cp')
			->distinct()
			->where('1 = 1')
			->groupBy('cp.code')
			// ->setMaxResults(100)
			->getQuery()
			->execute();
	} 
}
