<?php

namespace ProjectBundle\Repository\Common;

/**
 * ProjectGroupePilotageUsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectGroupePilotageUsersRepository extends \Doctrine\ORM\EntityRepository
{
}
