<?php

namespace ProjectBundle\Repository\Common;

/**
 * ProjectGroupeTravailusersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectGroupeTravailusersRepository extends \Doctrine\ORM\EntityRepository
{
}
