<?php

namespace ProjectBundle\Repository\Common;

/**
 * CrmDocsEnvoyesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectDocsRepository extends \Doctrine\ORM\EntityRepository
{
}
