<?php

namespace ProjectBundle\Repository\Common;

/**
 * ProjectGroupeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectGroupeRepository extends \Doctrine\ORM\EntityRepository
{
}
