<?php

namespace ProjectBundle\Repository\Common;

/**
 * ProjectEtapeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectEtapeRepository extends \Doctrine\ORM\EntityRepository
{
}
