<?php

namespace ProjectBundle\Repository\Common;

/**
 * ProjectsFiltersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectsFiltersRepository extends \Doctrine\ORM\EntityRepository
{
}
