<?php

namespace ProjectBundle\Repository\Common;

/**
 * ProjectEtapesOperationsIssuesRealisationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectEtapesOperationsIssuesRealisationsRepository extends \Doctrine\ORM\EntityRepository
{
}
