<?php

namespace ProjectBundle\Repository\Common;

/**
 * ProjectEtapesOperationsIssuesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectEtapesOperationsIssuesRepository extends \Doctrine\ORM\EntityRepository
{
}
