<?php

namespace ProjectBundle\Repository\Common;
use Doctrine\ORM\Query\Expr\Join;

/**
 * ProjectVersionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectVersionRepository extends \Doctrine\ORM\EntityRepository
{
	// get by project
	public function findbyProjet ($criteria) 
	{
		$return = $this->createQueryBuilder('v')
			->select('v')
			->innerJoin('ProjectBundle:Common\Project',
                'p',
                Join::WITH,
                'p.id = v.idProjet');
			
			$array = [];
			foreach($criteria as $key => $value)
				$array[] = "v.$key = :$key";
			$array = implode(' AND ', $array);
			$return->where($array);

			if( $criteria )
				foreach ($criteria as $key => $value)
					$return->setParameter("$key", $value);
        // return
        return $return->getQuery()->execute();
	}	
}