<?php

namespace ProjectBundle\Repository\Common;

/**
 * ProjectEtapesOperationsUsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectEtapesUsersRepository extends \Doctrine\ORM\EntityRepository
{
}
