<?php

namespace ProjectBundle\Repository\Common;

/**
 * ProjectEtapesOperationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectEtapesOperationsRepository extends \Doctrine\ORM\EntityRepository
{
}
