<?php

namespace ProjectBundle\Repository\Common;

/**
 * ProjectLivrablesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectLivrablesRepository extends \Doctrine\ORM\EntityRepository
{
}
