<?php

namespace ProjectBundle\Repository\Common;

/**
 * ProjectEtapesOperationsIssuesOrganisationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectEtapesOperationsIssuesOrganisationRepository extends \Doctrine\ORM\EntityRepository
{
}
