<?php

namespace ProjectBundle\Repository\Common;

/**
 * ProjectNotesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectNotesRepository extends \Doctrine\ORM\EntityRepository
{
}
