<?php

namespace ProjectBundle\Repository\Common;

/**
 * ProjectEtapesJalonsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectEtapesJalonsRepository extends \Doctrine\ORM\EntityRepository
{
}
