<?php

namespace ProjectBundle\Repository\Common;

/**
 * ProjectGroupesUsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectGroupesUsersRepository extends \Doctrine\ORM\EntityRepository
{
}
