<?php

namespace ProjectBundle\Repository\Common;

/**
 * ProjetEtapesOperationsRealisationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectEtapesOperationsRealisationsRepository extends \Doctrine\ORM\EntityRepository
{
}
