<?php

namespace UsersBundle\Repository;

use Doctrine\ORM\Query\Expr\Join;

/**
 * BusinessUnitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusinessUnitRepository extends \Doctrine\ORM\EntityRepository
{
	//================================
	// Relation Business User
	//================================
	public function findByUser ($user_id, $bu_id = 0) {
		$business = $this->createQueryBuilder('b');
			// ->innerJoin('UsersBundle:UserClient', 'u')

		// getting BU user => r_bu_user
		$business->innerJoin('UsersBundle:RelationBusinessUser', 'r', Join::WITH, 'r.iDBusinessUnit = b.id');
		$business->innerJoin('UsersBundle:UserClient', 'u', Join::WITH, 'r.iDUser = u.id');

		$business
			->where('u.id = :id')
			->setParameter('id', $user_id);

		if( $bu_id ) {
			$business
				->andwhere('b.id = :bu_id')
				->setParameter('bu_id', $bu_id);
		}
		return $business->getQuery()->execute();
	}
}
