<?php

namespace UsersBundle\Repository;

use Doctrine\ORM\Query\Expr\Join;

/**
 * BusinessUnitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusinessUnitRepository extends \Doctrine\ORM\EntityRepository
{
	//================================
	// Relation Business User
	//================================
	public function findByUser ($user_id) {
		$business = $this->createQueryBuilder('b');

		// getting BU user => r_bu_user
		$business->innerJoin('UsersBundle:RelationBusinessUser', 'r', Join::WITH, 'r.iDBusinessUnit = b.id');
		$business->innerJoin('UsersBundle:UserClient', 'u', Join::WITH, 'r.iDUser = u.id');

		$business->where('u.id = :id');
		$business->setParameter('id', $user_id);
		return $business->getQuery()->execute();
	}
}
