<?php

namespace UsersBundle\Repository;

/**
 * RelationBusinessEntiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RelationBusinessEntiteRepository extends \Doctrine\ORM\EntityRepository
{
}
