<?php

namespace UsersBundle\Repository;
use Doctrine\ORM\Query\Expr\Join;

/**
 * UserClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserClientRepository extends \Doctrine\ORM\EntityRepository
{
	//================================
	// ici nature = 2, est contact
	//================================
	public function findContact () {
		$contact = $this->createQueryBuilder('u')->where('u.iDNatureUser = :nature');
		$contact->setParameter('nature', 2);
		return $contact->getQuery()->execute();
	}

	//================================
	// ici nature = 1, est employé/salarié
	//================================
	public function findEmploye () {
		$contact = $this->createQueryBuilder('u')->where('u.iDNatureUser = :nature AND u.firstname <> \'%admin%\'');
		$contact->setParameter('nature', 1);
		return $contact->getQuery()->execute();
	}

	//================================
	// ici nature = 1, est employé/salarié avec critère
	//================================
	public function findContactBy ($criteria, $join) {

		if(!count($criteria)) return;
		$contact = $this->createQueryBuilder('u');

		$where = [];
		$where_join = ' 1 = 1 ';
		foreach($criteria as $key => $criter) {
			if( $criter && is_string($criter) ) $where[] = "u.{$key} LIKE :{$key}";
			else if( $criter ) $where[] = "u.{$key} = :{$key}";
		}

		if( $join == 'or') $where_join = implode(' OR ', $where);
		else $where_join = implode(' AND ', $where);

		$contact->where('(' . $where_join . ') AND u.iDNatureUser = 2');

		foreach($criteria as $key => $criter) {
			if( $criter && is_string($criter) )  $criter = "%$criter%";
			$contact->setParameter($key, $criter);
		}
		return $contact->getQuery()->execute();
	}

	public function findUsers ($user_id) {
		$users = $this->createQueryBuilder('u')
			->select('u', 'bu.nomBusinessUnit', 'c.raisonSociale')
			->innerJoin('UsersBundle:Users', 'ur', Join::WITH, 'ur.id = u.iDCompte')
			->innerJoin('UsersBundle:RelationBusinessUser', 'rbu', Join::WITH, 'rbu.iDUser = u.id')
			->innerJoin('UsersBundle:RelationBusinessEntite', 'rbe', Join::WITH, 'rbe.iDBusinessUnit = rbu.iDBusinessUnit')
			->leftJoin('UsersBundle:Back\UsersParamRelationsFonctions', 'relf', Join::WITH, 'relf.id = rbu.iDBusinessUnit')
			->leftJoin('UsersBundle:BusinessUnit', 'bu', Join::WITH, 'bu.id = rbu.iDBusinessUnit')
			->leftJoin('ClientBundle:Client', 'c', Join::WITH, 'c.id = rbe.iDentite')
			->leftJoin('UsersBundle:Back\UsersParamService', 's', Join::WITH, 's.id = relf.iDService')
			// ->where('u.iDNatureUser = 2 AND ur.id = :user_id')
			->where('ur.id = :user_id')
			->setParameter('user_id', $user_id)
			->getQuery()
			->execute();

		if( count($users) ) {
			foreach($users as $key => $user) {
				$relation = $this->createQueryBuilder('u')
					->select('relf')
					->innerJoin('UsersBundle:Users', 'ur', Join::WITH, 'ur.id = u.iDCompte')
					->innerJoin('UsersBundle:RelationBusinessUser', 'rbu', Join::WITH, 'rbu.iDUser = u.id')
					->innerJoin('UsersBundle:RelationBusinessEntite', 'rbe', Join::WITH, 'rbe.iDBusinessUnit = rbu.iDBusinessUnit')
					->leftJoin('UsersBundle:Back\UsersParamRelationsFonctions', 'relf', Join::WITH, 'relf.id = rbu.iDBusinessUnit')
					->where('u.id = :user_id')
					->setParameter('user_id', $user[0]->getId())
					->getQuery()
					->execute();

				if(count($relation))
					$users[$key]['fonction'] = $relation[0];

				$nature = $this->createQueryBuilder('u')
					->select('up')
					->innerJoin('UsersBundle:Users', 'ur', Join::WITH, 'ur.id = u.iDCompte')
					->innerJoin('UsersBundle:Back\UsersParamNature', 'up', Join::WITH, 'up.id = u.iDNatureUser')
					->where('u.id = :user_id')
					->setParameter('user_id', $user[0]->getId())
					->getQuery()
					->execute();

				if(count($nature))
					$users[$key]['nature'] = $nature[0];

				$service = $this->createQueryBuilder('u')
					->select('s')
					->innerJoin('UsersBundle:Users', 'ur', Join::WITH, 'ur.id = u.iDCompte')
					->innerJoin('UsersBundle:RelationBusinessUser', 'rbu', Join::WITH, 'rbu.iDUser = u.id')
					->innerJoin('UsersBundle:RelationBusinessEntite', 'rbe', Join::WITH, 'rbe.iDBusinessUnit = rbu.iDBusinessUnit')
					->leftJoin('UsersBundle:Back\UsersParamRelationsFonctions', 'relf', Join::WITH, 'relf.id = rbu.iDBusinessUnit')
					->leftJoin('UsersBundle:BusinessUnit', 'bu', Join::WITH, 'bu.id = rbu.iDBusinessUnit')
					->leftJoin('ClientBundle:Client', 'c', Join::WITH, 'c.id = rbe.iDentite')
					->leftJoin('UsersBundle:Back\UsersParamService', 's', Join::WITH, 's.id = relf.iDService')
					->where('u.id = :user_id')
					->setParameter('user_id', $user[0]->getId())
					->getQuery()
					->execute();

				if(count($service))
					$users[$key]['service'] = $service[0];
			}
		}
		return $users;
	}

	public function findBU ($id_user) {
		return $this->createQueryBuilder('u')
			->select('bu')
			->innerJoin('UsersBundle:Users', 'ur', Join::WITH, 'ur.id = u.iDCompte')
			->innerJoin('UsersBundle:RelationBusinessUser', 'rbu', Join::WITH, 'rbu.iDUser = u.id')
			->innerJoin('UsersBundle:BusinessUnit', 'bu', Join::WITH, 'bu.id = rbu.iDBusinessUnit')
			->where('ur.id = :id_user and u.iDNatureUser = 1')
			->setParameter('id_user', $id_user)
			->getQuery()
			->execute();
	}

	public function findUser ($user_id, $bu_id) {
		$return  = $this->createQueryBuilder('u')
			->innerJoin('UsersBundle:Users', 'ur', Join::WITH, 'ur.username = u.login')
			->where('u.id = :user_id');

		$param = [];
		if( $bu_id == -1 ) {
	 		$return->innerJoin('UsersBundle:RelationBusinessUser', 'rbu', Join::WITH, 'rbu.iDUser = u.id');
	 		$return->andWhere('AND rbu.iDBusinessUnit = :bu_id');
	 		$param['bu_id'] = $bu_id;
		}
	 	$param['user_id'] = $user_id;

	 	return $return->setParameters($param)
			->getQuery()
			->execute();
	}


	// getting all user the same name of user connected
	public function findByBU ($id_user) {
		if(!$id_user) return;
		
		// obtenir tout les utilisateur de même login que celui qui est logé
		$users = $this->createQueryBuilder('u')
			->innerJoin('UsersBundle:Users', 'ur', Join::WITH, 'ur.username = u.login')
		 	->innerJoin('UsersBundle:RelationBusinessUser', 'rbu', Join::WITH, 'rbu.iDUser = u.id')
		 	->where('u.login = :login')
		 	->setParameter('id_user', $id_user)
			->getQuery();

		return $users->execute();
	}

	// get by bu user
	public function findBBU ($iDCompte, $bu_id, $one_by = false) {
		$users = $this->createQueryBuilder('u')
		 	->innerJoin('UsersBundle:RelationBusinessUser', 'rbu', Join::WITH, 'rbu.iDUser = u.id')
		 	->where('u.iDCompte = :compte AND rbu.iDBusinessUnit = :bu_id')
		 	->setParameters(['compte' => $iDCompte, 'bu_id' => $bu_id]);
		$return = $users->getQuery()->execute();
		if(!count($return)) return null;

		if( $one_by ) $return = $return[0];
		return $return;
	}

	public function findSalarierParBU ($rbu_id = 0, $id_nature_user = 0) {
        $users = $this->createQueryBuilder('u')
        	->select('u.id', 'u.firstname', 'u.lastname', 'bu.nomBusinessUnit')
        	// SELECT * FROM user_client
        	->innerJoin('UsersBundle:Back\UsersParamNature', 'upn', Join::WITH, 'upn.id = u.iDNatureUser')
			// INNER JOIN param_user_nature ON param_user_nature.IDNatureUser = USER.IDNatureUser
			->innerJoin('UsersBundle:RelationBusinessUser', 'rbu', Join::WITH, 'rbu.iDUser = u.id')
			// INNER JOIN R_BU_User ON R_BU_User.IDUser = USER.IDUser
			->innerJoin('UsersBundle:Back\UsersParamRelationsFonctions', 'urf', Join::WITH, 'urf.id = rbu.iDRelation_Fonctionnelle')
			// INNER JOIN relations_fonctions ON relations_fonctions.ID = R_BU_User.IDRelation_Fonctionnelle
			->innerJoin('UsersBundle:BusinessUnit', 'bu', Join::WITH, 'bu.id = rbu.iDBusinessUnit')
			// INNER JOIN BusinessUnit ON BusinessUnit.IDBusinessUnit = R_BU_User.IDBusinessUnit
			->leftJoin('UsersBundle:RelationUserEntite', 'rue', Join::WITH, 'rue.iDUser = u.id')
			// LEFT JOIN r_user_entite_j ON r_user_entite_j.IDUser = USER.IDUser
			->leftJoin('UsersBundle:RelationBusinessEntite', 'rbe', Join::WITH, 'rbe.id = rue.iDUserEntite')
			// LEFT JOIN r_bu_entitej ON r_bu_entitej.ID = r_user_entite_j.Id_r_bu_entitej
			->leftJoin('ClientBundle:Client', 'c', Join::WITH, 'c.id = rue.idEntiteJ')
			// LEFT JOIN client ON client.IDEntite = r_user_entite_j.IdEntiteJ
			->leftJoin('UsersBundle:Back\UsersParamRelationsProfessionnelles', 'urp', Join::WITH, 'urp.id = rbe.iDRelationsProfessionnelles')
			// LEFT JOIN Relations_Professionnelles ON Relations_Professionnelles.IDRelations_Professionnelles = r_bu_entitej.IDRelations_Professionnelles
			->where('u.iDNatureUser = 1');
			
		if( $rbu_id != 0 )
			$users->andWhere('bu.id = :rbu_id'); //=== to find salarié par BU ===//

		// WHERE USER.IDNatureUser = 1 AND R_BU_User.IDBusinessUnit = 2 
		if( $rbu_id != 0 )
			$users->setParameter('rbu_id', $rbu_id);

		$return = $users->getQuery()->execute();
		if(count($return)) 
			foreach($return as $key => $retour) {
				$urf = $this->createQueryBuilder('u')->select('urf')
				// SELECT * FROM user_client
	        	->innerJoin('UsersBundle:Back\UsersParamNature', 'upn', Join::WITH, 'upn.id = u.iDNatureUser')
				// INNER JOIN param_user_nature ON param_user_nature.IDNatureUser = USER.IDNatureUser
				->innerJoin('UsersBundle:RelationBusinessUser', 'rbu', Join::WITH, 'rbu.iDUser = u.id')
				// INNER JOIN R_BU_User ON R_BU_User.IDUser = USER.IDUser
				->innerJoin('UsersBundle:Back\UsersParamRelationsFonctions', 'urf', Join::WITH, 'urf.id = rbu.iDRelation_Fonctionnelle')
				// INNER JOIN relations_fonctions ON relations_fonctions.ID = R_BU_User.IDRelation_Fonctionnelle
				->innerJoin('UsersBundle:BusinessUnit', 'bu', Join::WITH, 'bu.id = rbu.iDBusinessUnit')
				// INNER JOIN BusinessUnit ON BusinessUnit.IDBusinessUnit = R_BU_User.IDBusinessUnit
				->leftJoin('UsersBundle:RelationUserEntite', 'rue', Join::WITH, 'rue.iDUser = u.id')
				// LEFT JOIN r_user_entite_j ON r_user_entite_j.IDUser = USER.IDUser
				->leftJoin('UsersBundle:RelationBusinessEntite', 'rbe', Join::WITH, 'rbe.id = rue.iDUserEntite')
				// LEFT JOIN r_bu_entitej ON r_bu_entitej.ID = r_user_entite_j.Id_r_bu_entitej
				->leftJoin('ClientBundle:Client', 'c', Join::WITH, 'c.id = rue.idEntiteJ')
				// LEFT JOIN client ON client.IDEntite = r_user_entite_j.IdEntiteJ
				->leftJoin('UsersBundle:Back\UsersParamRelationsProfessionnelles', 'urp', Join::WITH, 'urp.id = rbe.iDRelationsProfessionnelles')
				// LEFT JOIN Relations_Professionnelles ON Relations_Professionnelles.IDRelations_Professionnelles = r_bu_entitej.IDRelations_Professionnelles
				->where('u.iDNatureUser = 1 and u.id = :user_id and bu.nomBusinessUnit = :bu_name')
				->setParameter('user_id', $retour['id'])
				->setParameter('bu_name', $retour['nomBusinessUnit'])
				->getQuery()
				->execute();

				if(count($urf))
					$return[$key][] = $urf[0];
			}

		return $return;
    }

    public function findSalarierCom ($urf_id) {
        $users = $this->createQueryBuilder('u')
        	->select('u.id', 'u.firstname', 'u.lastname')
        	// SELECT * FROM user_client
        	->innerJoin('UsersBundle:Back\UsersParamNature', 'upn', Join::WITH, 'upn.id = u.iDNatureUser')
			// INNER JOIN param_user_nature ON param_user_nature.IDNatureUser = USER.IDNatureUser
			->innerJoin('UsersBundle:RelationBusinessUser', 'rbu', Join::WITH, 'rbu.iDUser = u.id')
			// INNER JOIN R_BU_User ON R_BU_User.IDUser = USER.IDUser
			->innerJoin('UsersBundle:Back\UsersParamRelationsFonctions', 'urf', Join::WITH, 'urf.id = rbu.iDRelation_Fonctionnelle')
			// INNER JOIN relations_fonctions ON relations_fonctions.ID = R_BU_User.IDRelation_Fonctionnelle
			->innerJoin('UsersBundle:BusinessUnit', 'bu', Join::WITH, 'bu.id = rbu.iDBusinessUnit')
			// INNER JOIN BusinessUnit ON BusinessUnit.IDBusinessUnit = R_BU_User.IDBusinessUnit
			->leftJoin('UsersBundle:RelationUserEntite', 'rue', Join::WITH, 'rue.iDUser = u.id')
			// LEFT JOIN r_user_entite_j ON r_user_entite_j.IDUser = USER.IDUser
			->leftJoin('UsersBundle:RelationBusinessEntite', 'rbe', Join::WITH, 'rbe.id = rue.iDUserEntite')
			// LEFT JOIN r_bu_entitej ON r_bu_entitej.ID = r_user_entite_j.Id_r_bu_entitej
			->leftJoin('ClientBundle:Client', 'c', Join::WITH, 'c.id = rue.idEntiteJ')
			// LEFT JOIN client ON client.IDEntite = r_user_entite_j.IdEntiteJ
			->leftJoin('UsersBundle:Back\UsersParamRelationsProfessionnelles', 'urp', Join::WITH, 'urp.id = rbe.iDRelationsProfessionnelles')
			// LEFT JOIN Relations_Professionnelles ON Relations_Professionnelles.IDRelations_Professionnelles = r_bu_entitej.IDRelations_Professionnelles
			->where('u.iDNatureUser = 1');

		if(count($urf_id) > 0)
			foreach($urf_id as $urf)
				$users->andWhere("urf.id = :r_$urf");
		
		// WHERE USER.IDNatureUser = 1 AND R_BU_User.IDBusinessUnit = 2
		if(count($urf_id) > 0)
			foreach($urf_id as $urf)
				$users->setParameter("r_$urf", $urf);

		$return = $users->getQuery()->execute();
		if(count($return)) 
			foreach($return as $key => $retour) {
				$urf = $this->createQueryBuilder('u')->select('urf')
				// SELECT * FROM user_client
	        	->innerJoin('UsersBundle:Back\UsersParamNature', 'upn', Join::WITH, 'upn.id = u.iDNatureUser')
				// INNER JOIN param_user_nature ON param_user_nature.IDNatureUser = USER.IDNatureUser
				->innerJoin('UsersBundle:RelationBusinessUser', 'rbu', Join::WITH, 'rbu.iDUser = u.id')
				// INNER JOIN R_BU_User ON R_BU_User.IDUser = USER.IDUser
				->innerJoin('UsersBundle:Back\UsersParamRelationsFonctions', 'urf', Join::WITH, 'urf.id = rbu.iDRelation_Fonctionnelle')
				// INNER JOIN relations_fonctions ON relations_fonctions.ID = R_BU_User.IDRelation_Fonctionnelle
				->innerJoin('UsersBundle:BusinessUnit', 'bu', Join::WITH, 'bu.id = rbu.iDBusinessUnit')
				// INNER JOIN BusinessUnit ON BusinessUnit.IDBusinessUnit = R_BU_User.IDBusinessUnit
				->leftJoin('UsersBundle:RelationUserEntite', 'rue', Join::WITH, 'rue.iDUser = u.id')
				// LEFT JOIN r_user_entite_j ON r_user_entite_j.IDUser = USER.IDUser
				->leftJoin('UsersBundle:RelationBusinessEntite', 'rbe', Join::WITH, 'rbe.id = rue.iDUserEntite')
				// LEFT JOIN r_bu_entitej ON r_bu_entitej.ID = r_user_entite_j.Id_r_bu_entitej
				->leftJoin('ClientBundle:Client', 'c', Join::WITH, 'c.id = rue.idEntiteJ')
				// LEFT JOIN client ON client.IDEntite = r_user_entite_j.IdEntiteJ
				->leftJoin('UsersBundle:Back\UsersParamRelationsProfessionnelles', 'urp', Join::WITH, 'urp.id = rbe.iDRelationsProfessionnelles')
				// LEFT JOIN Relations_Professionnelles ON Relations_Professionnelles.IDRelations_Professionnelles = r_bu_entitej.IDRelations_Professionnelles
				->where('u.iDNatureUser = 1 and u.id = :user_id')
				->setParameter('user_id', $retour['id'])
				->getQuery()
				->execute();

				if(count($urf))
					$return[$key][] = $urf[0];
			}
		return $return;
    }

    /**
     * 
     * @param  integer $id_entite_juridique l'id du client en personne
     * @return Array   tableau d'objet ou null
     */
    public function findContactsClient ($id_entite_juridique) {
    	$users = $this->createQueryBuilder('u')
    		->select('u.id, u.firstname, u.lastname')
        	// SELECT * FROM user_client
        	->innerJoin('UsersBundle:Back\UsersParamNature', 'upn', Join::WITH, 'upn.id = u.iDNatureUser')
			// INNER JOIN param_user_nature ON param_user_nature.IDNatureUser = USER.IDNatureUser
			->innerJoin('UsersBundle:RelationBusinessUser', 'rbu', Join::WITH, 'rbu.iDUser = u.id')
			// INNER JOIN R_BU_User ON R_BU_User.IDUser = USER.IDUser
			// INNER JOIN BusinessUnit ON BusinessUnit.IDBusinessUnit = R_BU_User.IDBusinessUnit
			->innerJoin('UsersBundle:RelationUserEntite', 'rue', Join::WITH, 'rue.iDUser = u.id')
			->innerJoin('UsersBundle:Back\UsersParamRelationsFonctions', 'urf', Join::WITH, 'urf.id = rue.iDRelationFonctionnelle')
			// INNER JOIN relations_fonctions ON relations_fonctions.ID = R_BU_User.IDRelation_Fonctionnelle
			->innerJoin('UsersBundle:BusinessUnit', 'bu', Join::WITH, 'bu.id = rbu.iDBusinessUnit')
			
			// LEFT JOIN r_user_entite_j ON r_user_entite_j.IDUser = USER.IDUser
			->leftJoin('UsersBundle:RelationBusinessEntite', 'rbe', Join::WITH, 'rbe.id = rue.iDUserEntite')
			// LEFT JOIN r_bu_entitej ON r_bu_entitej.ID = r_user_entite_j.Id_r_bu_entitej
			->leftJoin('ClientBundle:Client', 'c', Join::WITH, 'c.id = rue.idEntiteJ')
			->where('c.id = :c_id and u.iDNatureUser = 2')
			// WHERE USER.IDNatureUser = 1 AND R_BU_User.IDBusinessUnit = 2 
			->setParameter('c_id', $id_entite_juridique);

		$return = $users->getQuery()->execute();
		if(count($return)) 
			foreach($return as $key => $retour) {
				$urf = $this->createQueryBuilder('u')->select('urf')
	        	// SELECT * FROM user_client
	        	->innerJoin('UsersBundle:Back\UsersParamNature', 'upn', Join::WITH, 'upn.id = u.iDNatureUser')
				// INNER JOIN param_user_nature ON param_user_nature.IDNatureUser = USER.IDNatureUser
				->innerJoin('UsersBundle:RelationBusinessUser', 'rbu', Join::WITH, 'rbu.iDUser = u.id')
				// INNER JOIN R_BU_User ON R_BU_User.IDUser = USER.IDUser
				// INNER JOIN BusinessUnit ON BusinessUnit.IDBusinessUnit = R_BU_User.IDBusinessUnit
				->innerJoin('UsersBundle:RelationUserEntite', 'rue', Join::WITH, 'rue.iDUser = u.id')
				->innerJoin('UsersBundle:Back\UsersParamRelationsFonctions', 'urf', Join::WITH, 'urf.id = rue.iDRelationFonctionnelle')
				// INNER JOIN relations_fonctions ON relations_fonctions.ID = R_BU_User.IDRelation_Fonctionnelle
				->innerJoin('UsersBundle:BusinessUnit', 'bu', Join::WITH, 'bu.id = rbu.iDBusinessUnit')
				
				// LEFT JOIN r_user_entite_j ON r_user_entite_j.IDUser = USER.IDUser
				->leftJoin('UsersBundle:RelationBusinessEntite', 'rbe', Join::WITH, 'rbe.id = rue.iDUserEntite')
				// LEFT JOIN r_bu_entitej ON r_bu_entitej.ID = r_user_entite_j.Id_r_bu_entitej
				->leftJoin('ClientBundle:Client', 'c', Join::WITH, 'c.id = rue.idEntiteJ')
				->where('u.iDNatureUser = 2 and u.id = :user_id')
				->setParameter('user_id', $retour['id'])
				->getQuery()
				->execute();

				if(count($urf))
					$return[$key][] = $urf[0];
			}
		return $return;
    }
}
