<?php

namespace UsersBundle\Repository;

/**
 * UserNotesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserNotesRepository extends \Doctrine\ORM\EntityRepository
{
}
