<?php

namespace UsersBundle\Repository;

/**
 * UsersSessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersSessionRepository extends \Doctrine\ORM\EntityRepository
{
	// update userSession
	public function Update( $id_session ) 
	{
		$update = $this->getEntityManager()->createQueryBuilder();
		return $update->update('UsersBundle:UsersSession', 'us')
		    ->set('us.date', ':now')
		    ->where($update->expr()->eq('us.id', ':us_id'))
		    ->setParameter('us_id', $id_session)
		    ->setParameter('now', (new \DateTime('now'))->format('Y-m-d H:i:s'))
		    ->getQuery()
		    ->execute();
	}
}
