<?php

namespace UsersBundle\Repository;

/**
 * UserParamServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserParamServiceRepository extends \Doctrine\ORM\EntityRepository
{
}
