<?php

namespace UsersBundle\Repository;

/**
 * UserDocsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserDocsRepository extends \Doctrine\ORM\EntityRepository
{
}
