<?php

namespace UsersBundle\Repository;

/**
 * UserParamGroupeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserParamGroupeRepository extends \Doctrine\ORM\EntityRepository
{
}
