<?php

namespace UsersBundle\Repository\Back;

/**
 * ParamServicesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParamServicesRepository extends \Doctrine\ORM\EntityRepository
{
}
