<?php

namespace UsersBundle\Repository\Back;

/**
 * UsersParamRelationsFonctionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersParamRelationsFonctionsRepository extends \Doctrine\ORM\EntityRepository
{
	
}
