<?php

namespace UsersBundle\Repository\Back;

use Doctrine\ORM\Query\Expr\Join;

/**
 * UsersParamRelationsFonctionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersParamRelationsProfessionnellesRepository extends \Doctrine\ORM\EntityRepository
{
	//=========================================
	// Relation Business User Professionnelles
	//=========================================
	public function findByUser ($user_id) {
		$business = $this->createQueryBuilder('b');

		// getting BU user => r_bu_user
		$business->innerJoin('UsersBundle:RelationBusinessEntite', 'r', Join::WITH, 'r.iDRelationsProfessionnelles = b.id');
		$business->innerJoin('UsersBundle:RelationBusinessUser', 'ru', Join::WITH, 'r.iDBusinessUnit = ru.iDBusinessUnit');
		$business->innerJoin('UsersBundle:UserClient', 'u', Join::WITH, 'ru.iDUser = u.id');

		$business->where('u.id = :id');
		$business->setParameter('id', $user_id);
		return $business->getQuery()->execute();
	}
}

