<?php

namespace UsersBundle\Repository\Back;

/**
 * UsersParamNatureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersParamNatureRepository extends \Doctrine\ORM\EntityRepository
{
}
